# Generated by Django 4.1.4 on 2022-12-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Blog',
            fields=[
                ('U_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Desc', models.CharField(max_length=2000)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Author', models.CharField(default='Gaurav', max_length=50)),
            ],
        ),
    ]
